"""
csv_to_data.py
--------------
Converts an icon_inventory CSV into a data-{repo}.js file for index.html.

Use this when you have an existing CSV (or have edited one by hand) and want
to regenerate the JS without re-running a full codebase scan.

Usage:
  python csv_to_data.py --csv icon_inventory.csv --repo 3dviewer
  python csv_to_data.py --csv icon_inventory-portal-fe.csv --repo portal-fe --out data-portal-fe.js
  python csv_to_data.py --csv icon_inventory-3dviewer.csv --repo 3dviewer --out data-3dviewer.js
  python csv_to_data.py --csv icon_inventory-settings-ui.csv --repo settings-ui --out data-settings-ui.js

The script also scans the extracted/ folder (sibling of the output JS) and
rebuilds the extractedAssets map so the viewer can use local SVG copies.
"""

import os
import csv
import json
import re
import argparse
from collections import Counter
from datetime import date
from pathlib import Path


# ---------------------------------------------------------------------------
# Helpers (kept in sync with scrape_icons.py)
# ---------------------------------------------------------------------------

def safe_asset_name(repo: str, file_path: str) -> str:
    """Same naming convention as scrape_icons.py — used to match extracted files."""
    clean = file_path.replace("\\", "/").replace("/", "__")
    clean = re.sub(r"[^A-Za-z0-9_.-]+", "_", clean)
    return f"{repo}__{clean}"


def rebuild_extracted_assets(repo: str, out_dir: Path, rows: list) -> dict:
    """
    Read the mapped assets accurately from the {repo}-assets.json file generated by scrape_icons.py.
    Returns {original_rel_path: "extracted/filename.ext"}.
    """
    json_path = out_dir / f"{repo}-assets.json"
    if json_path.exists():
        with open(json_path, "r", encoding="utf-8") as f:
            return json.load(f)
    print(f"  [WARN] {json_path.name} not found, some assets might not map correctly.")
    return {}


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Convert an icon inventory CSV to a data-{repo}.js file."
    )
    parser.add_argument(
        "--csv",
        required=True,
        help="Path to the icon inventory CSV.",
    )
    parser.add_argument(
        "--repo",
        required=True,
        help="Repo key (e.g. 3dviewer, portal-fe, settings-ui). "
             "Controls the output filename and extracted-asset prefix.",
    )
    parser.add_argument(
        "--out",
        default=None,
        help="Output JS file path. Defaults to data-{repo}.js next to the CSV.",
    )
    args = parser.parse_args()

    csv_path = Path(args.csv).resolve()
    if not csv_path.exists():
        print(f"[ERROR] CSV not found: {csv_path}")
        return

    repo = args.repo
    out_path = Path(args.out).resolve() if args.out else csv_path.parent / f"data-{repo}.js"

    # ── Read CSV ──────────────────────────────────────────────────
    rows_raw = []
    with open(csv_path, "r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows_raw.append(row)

    if not rows_raw:
        print(f"[WARN] CSV is empty: {csv_path}")

    # ── Summary stats ─────────────────────────────────────────────
    by_type = Counter(r.get("type", "") for r in rows_raw)
    by_lib = Counter(r["library"] for r in rows_raw if r.get("library"))
    unique_svgs = len({r["icon_name"] for r in rows_raw if r.get("type") == "SVG_import"})
    unique_react = len({r["icon_name"] for r in rows_raw if r.get("type") == "ReactIcons"})

    # ── Row arrays: [file, line, type, library, icon_name, context, label] ──
    rows = [
        [
            r.get("file", ""),
            r.get("line", ""),
            r.get("type", ""),
            r.get("library", ""),
            r.get("icon_name", ""),
            r.get("context", ""),
            r.get("label", ""),
        ]
        for r in rows_raw
    ]

    # ── Rebuild extractedAssets from extracted/ folder ────────────
    extracted_assets = rebuild_extracted_assets(repo, out_path.parent, rows_raw)

    # ── Build data object ─────────────────────────────────────────
    data_obj = {
        "generated": date.today().isoformat(),
        "total": len(rows),
        "uniqueSVGs": unique_svgs,
        "uniqueReact": unique_react,
        "byType": dict(by_type),
        "byLib": dict(by_lib),
        "rows": rows,
        "extractedAssets": extracted_assets,
    }

    # ── Write JS ──────────────────────────────────────────────────
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by csv_to_data.py — do not edit by hand\n")
        f.write(f"// Generated: {data_obj['generated']}\n")
        f.write("window.ICON_DATA = ")
        f.write(json.dumps(data_obj, indent=2, ensure_ascii=False))
        f.write(";\n")

    print(f"\n  Repo         : {repo}")
    print(f"  CSV          : {csv_path}")
    print(f"  Output       : {out_path}")
    print(f"  Total rows   : {len(rows)}")
    print(f"  By type      : {dict(by_type)}")
    print(f"  Extracted SVGs mapped: {len(extracted_assets)}\n")


if __name__ == "__main__":
    main()
