// data.js — Dataset loading, repo config helpers, and extracted-asset URL resolution

// ── Data ──────────────────────────────────────────────────────
// Populated by data-*.js (generated by scrape_icons.py)
const DATASETS = window.ICON_DATASETS || (window.ICON_DATA ? { default: window.ICON_DATA } : {});
const REPO_CONFIG = window.ICON_REPOS || {};
const REPO_ORDER = window.ICON_REPO_ORDER || Object.keys(DATASETS);

function getRepoConfig(key) {
  return REPO_CONFIG[key] || { label: key, root: key };
}
function getRepoLabel(key) {
  const cfg = getRepoConfig(key);
  return cfg.label || key;
}
function getRepoRoot(key) {
  const cfg = getRepoConfig(key);
  return cfg.root || '';
}
function getRepoDisplayRoot(key) {
  const root = String(getRepoRoot(key) || '').replace(/\\/g, '/');
  if (!root) return key;
  return root.replace(/^\.\//, '').replace(/^\.\.\//, '');
}
function buildRepoPath(key, file) {
  const displayRoot = getRepoDisplayRoot(key);
  const cleanFile = String(file || '').replace(/\\/g, '/');
  if (!displayRoot) return cleanFile;
  if (!cleanFile) return displayRoot;
  return `${displayRoot}/${cleanFile}`.replace(/\/+/g, '/');
}

const DATASET_LIST = REPO_ORDER
  .map(key => ({ key, ds: DATASETS[key] }))
  .filter(entry => entry.ds && Array.isArray(entry.ds.rows));

const RAW = [];
DATASET_LIST.forEach(({ key, ds }) => {
  ds.rows.forEach(r => {
    RAW.push({
      repo: key,
      repoLabel: getRepoLabel(key),
      repoRoot: getRepoRoot(key),
      repoPath: buildRepoPath(key, r[0]),
      file: r[0],
      line: r[1],
      type: r[2],
      library: r[3],
      icon_name: r[4],
      context: r[5],
      label: r[6] || ''
    });
  });
});

function aggregateDatasets(list) {
  const agg = {
    generated: '',
    total: 0,
    uniqueSVGs: 0,
    uniqueReact: 0,
    byType: {},
    byLib: {}
  };
  const genParts = [];
  list.forEach(({ key, ds }) => {
    if (!ds) return;
    agg.total += ds.total || (ds.rows ? ds.rows.length : 0);
    agg.uniqueSVGs += ds.uniqueSVGs || 0;
    agg.uniqueReact += ds.uniqueReact || 0;
    Object.entries(ds.byType || {}).forEach(([type, count]) => {
      agg.byType[type] = (agg.byType[type] || 0) + count;
    });
    Object.entries(ds.byLib || {}).forEach(([lib, count]) => {
      agg.byLib[lib] = (agg.byLib[lib] || 0) + count;
    });
    if (ds.generated) genParts.push(`${getRepoLabel(key)}: ${ds.generated}`);
  });
  agg.generated = genParts.join(' • ');
  return agg;
}

const AGG = aggregateDatasets(DATASET_LIST);


function buildAssetUrl(repo, file) {
  const base = getRepoRoot(repo) || '../app';
  const cleanBase = String(base || '').replace(/\\/g, '/').replace(/\/$/, '');
  const cleanFile = String(file || '').replace(/\\/g, '/').replace(/^\/+/, '');
  if (!cleanBase) return cleanFile;
  return `${cleanBase}/${cleanFile}`.replace(/\/+/g, '/');
}

// Lookup map: "repo||normalized/file/path" -> "extracted/repo__path__file.svg"
// Populated from extractedAssets written by scrape_icons.py into each data-*.js
const EXTRACTED_ASSETS = {};
DATASET_LIST.forEach(({ key, ds }) => {
  if (!ds || !ds.extractedAssets) return;
  Object.entries(ds.extractedAssets).forEach(([file, extractedPath]) => {
    const normFile = String(file || '').replace(/\\/g, '/').replace(/\/+/g, '/').replace(/^\//, '');
    EXTRACTED_ASSETS[`${key}||${normFile}`] = extractedPath;
  });
});

// Prefer an extracted local copy; fall back to the original repo URL.
function resolveAssetUrl(repo, file) {
  const normFile = String(file || '').replace(/\\/g, '/').replace(/\/+/g, '/').replace(/^\//, '');
  const extracted = EXTRACTED_ASSETS[`${repo}||${normFile}`];
  return extracted || buildAssetUrl(repo, file);
}
